services:
  postgres-ordenes:
    image: postgres:16
    container_name: eventpass-ordenes-db
    environment:
      POSTGRES_DB: ordenes_db
      POSTGRES_USER: eventpass
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5435:5432"
    volumes:
      - ordenes_data:/var/lib/postgresql/data

volumes:
  ordenes_data:
